### ISSUE TITLE
Error: init.js does not exist in this template

### ISSUE THREAD

**Issue by adnoh** [carrot/roots-template-blog#2]
When creating a new instance of this template I get the above error message.
No Idea how to compile the coffeescript to the require js or why roots isn't this doing by itself.
btw...the template looks like it's really outdated (for Example I get: Transformers.markdown is deprecated, you must replace the :markdown jade filter, with :marked and install jstransformer-marked before you update to jade@2.0.0)

Workaround:
npm i sprout-cli@0.0.2
sprout add blog https://github.com/carrot/roots-template-blog
sprout init blog example-blog
npm i sprout-cli
cd example-blog
npm install

**Comment by jescalan** [comment]
Hi there!

Yes, this template is extremely outdated. I'll push an update today and get it patched up!

**Comment by jescalan** [comment]
Fixed! 🎉
